name: Github Packages UI Library Actions

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2

              with:
                  node-version: 21
            - run: npm ci
            - run: npm test

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2

              with:
                  node-version: 21
                  registry-url: https://npm.pkg.github.com/
                  scope: "@bludevkit"
            - run: npm ci
            - run: npm run build
            - run: |
                git config --global user.email "coding.ymaro@gmail.com"
                git config --global user.name "Ymaro Blue"
            - run: npm run release
              env:
                  GITHUB_TOKEN: ${{secrets.VUE_UI_TOKEN}}
